changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Added
      labels:
        - feature
        - enhancement
    - title: Fixed
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Maintenance
      labels:
        - dependencies
        - chore
        - ci
    - title: Other Changes
      labels:
        - "*"
